=== TIData/OefeningenDBII/VoetbalPloegen/voetbal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ploegen" type="ploegenType"/>
  <xs:element name="ploeg" type="ploegType"/>
  <xs:element name="clubnaam" type="naamType"/>
  <xs:element name="email" type="emailType" />
  <xs:element name="website" type="xs:anyURI" />
  <xs:element name="klasse" type="klasseType"/>
  <xs:element name="trainer" type="persoonsType" />
  <xs:element name="voornaam" type="naamType"/>
  <xs:element name="familienaam" type="naamType"/>
  <xs:element name="spelers" type="spelersType" />
  <xs:element name="speler" type="spelerType" />
  <xs:element name="naam" type="persoonsType"/>
  <xs:element name="geboortedatum" type="geboortedatumType"/>
  <xs:element name="nationaliteit" type="nationaliteitType"/>
  <xs:element name="international" type="internationalType"/>
  <xs:attribute name="stamnummer" type="stamnummerType" />


  <xs:simpleType name="naamType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="stamnummerType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="9500" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\w*\.\w*@\w*\.\w{2,3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="klasseType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Jupiler Pro League"/>
      <xs:enumeration value="Tweede klasse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="geboortedatumType">
    <xs:restriction base="xs:date">
      <xs:minInclusive value="1972-01-01" />
      <xs:maxExclusive value="2000-01-01" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="nationaliteitType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+(/[a-zA-Z]+)?" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="internationalType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="J"/>
      <xs:enumeration value="N"/>
    </xs:restriction>
  </xs:simpleType>
  

  <xs:complexType name="ploegenType">
    <xs:sequence>
      <xs:element ref="ploeg" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="spelersType">
    <xs:sequence>
      <xs:element ref="speler" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="spelerType">
    <xs:sequence>
      <xs:element ref="naam"></xs:element>
      <xs:element ref="geboortedatum"></xs:element>
      <xs:element ref="nationaliteit"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="persoonsType">
    <xs:all>
      <xs:element ref="voornaam" />
      <xs:element ref="familienaam" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="ploegType">
    <xs:sequence>
      <xs:element ref="clubnaam" />
      <xs:element ref="email" />
      <xs:element ref="website" minOccurs="0" />
      <xs:element ref="klasse" />
      <xs:element ref="trainer" />
      <xs:element ref="spelers" />
    </xs:sequence>
    <xs:attribute ref="stamnummer" use="required"/>
  </xs:complexType>
  
</xs:schema>

=== TIData/OefeningenDBII/VoetbalPloegen/voetbal.xml
<?xml version="1.0" encoding="utf-8"?>  
<ploegen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="voetbal.xsd">
  <ploeg stamnummer="3">
    <clubnaam>Club Brugge</clubnaam>
    <email>info@clubbrugge.be</email>
    <website>www.clubbrugge.be</website>
    <klasse>Jupiler Pro League</klasse>
    <trainer>
      <voornaam>Michel</voornaam>
      <familienaam>Preud'homme</familienaam>
    </trainer>
    <spelers>
       <speler>
          <naam>
            <voornaam>Timmy</voornaam>
            <familienaam>Simons</familienaam>
          </naam>
          <geboortedatum>1976-12-11</geboortedatum>
          <nationaliteit>Belg</nationaliteit>
      </speler>

      <speler>
        <naam>
          <voornaam>Abdoulay</voornaam>
          <familienaam>Diaby</familienaam>
        </naam>
        <geboortedatum>1791-03-21</geboortedatum>
        <nationaliteit>Malinees/Frans</nationaliteit>
        <international>J</international>
      </speler>
    </spelers>
  </ploeg>
  <ploeg stamnummer="700000">
    <clubnaam>K.M.S.K. Deinze</clubnaam>
    <email>info@kmskdeinze.be</email>
    <website>www.kmskdeinze.be</website>
    <klasse>Tweede klasse</klasse>
    <trainer>
       <voornaam>Geoffrey</voornaam>
       <familienaam>Claes</familienaam>
    </trainer>
    <spelers>
      <speler>
        <naam>
          <voornaam>Sandro</voornaam>
          <familienaam>Calabro</familienaam>
        </naam>
        <geboortedatum>1984-08-15</geboortedatum>
        <nationaliteit>Spaans/Belg</nationaliteit>
        <international>N</international>
      </speler>
    </spelers>
  </ploeg>
</ploegen>
